### ISSUE TITLE
e2e and unit test case inclusion 

### ISSUE THREAD

**Issue by tapas4java** [rolandjitsu/ng2-play#3]
At least one one unit and e2e test case inclusion  will be great help

**Comment by rolandjitsu** [comment]
@tapas4java I was planning on doing this once I wrap up the other things I am working on.

**Comment by tapas4java** [comment]
Awesome! Thanks.

**Comment by Raker** [comment]
Test examples would be amazing, is that being implemented soon? Not to rush, just curious.

**Comment by rolandjitsu** [comment]
@Raker I am waiting until a more stable release.
