### ISSUE TITLE
todo items are not rendered

### ISSUE THREAD

**Issue by rolandjitsu** [rolandjitsu/ng2-play#5]

**Comment by r-park** [comment]
Hi, the following change seems to resolve the item rendering issue:
```javascript
// common/shadow_dom.ts

export const shadowDomInjectables: Array<any> = !isNativeShadowDOMSupported ? [] : [
  //bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)
  NativeShadowDomStrategy
];
```
And this change resolved a related issue caused by `this.el.shadowRoot` being `null`:
```javascript
// app/components/icon/icon.ts

set src(src: string) {
  //let root;
  //if (isNativeShadowDOMSupported) root = this.el.shadowRoot;
  //else root = this.el;
  this.icon.get(src).then((svg) => {
    //root.appendChild(svg);
    this.el.appendChild(svg);
  });
}
```

**Comment by rolandjitsu** [comment]
@r-park that doesn't really solve the issue. It just doesn't use `NativeShadowDomStrategy` anymore which makes the icons work again, but that is not really what I am looking for.

I would still like to have Shadow DOM used if supported and the icons work properly no matter if Shadow DOM is used or not.

I will have to take a look into it, but I also reported it as [#3222](https://github.com/angular/angular/issues/3222) and hopefully I will get some insight on what is going on.
